spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://username:password@cluster.mongodb.net/code-review-assistant?appName=devrel-article-java-springai-codereview}

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.embedding.options.model=text-embedding-3-small
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.temperature=0.2
